### ISSUE TITLE
error with amplify mock after adding lambda function resolver

### ISSUE THREAD

**Issue by imgntn** [dabit3/aws-appsync-react-workshop#3]
I'm pretty sure `amplify mock` worked for me yesterday, because I was able to use the graphQL interface to get the coins, but when i try to run it today, i get this error

```Creating table TalkTable locally
Creating table CommentTable locally
Failed to start API Mock endpoint Error: Lambda function currencyfunction does not exist in your project.
Please run amplify add function
```

I ran into this same problem on my own project a few days ago.  Commented on the closest issue I could find.

https://github.com/aws-amplify/amplify-cli/issues/2280

Thanks for the great workshops!! :)

**Comment by imgntn** [comment]
nevermind, total user error i'd accidentally deleted index.js from that folder somehow.  i also worked around #2280 with adding the graphql endpoints to my function parameters json manually, which seems strange but works.  thanks!!

**Comment by johnnyoshika** [comment]
Strangely I get this exact same error. My `index.js` is still there, so I'm a little stumped why I get this error:

```
Creating table TalkTable locally
Creating table CommentTable locally
Failed to start API Mock endpoint Error: Lambda function currencyfunction does not exist in your project.
Please run amplify add function
```

**Comment by johnnyoshika** [comment]
My problem was solved when I regenerated my function with the same function name for my project and lambda as explained here: https://github.com/aws-amplify/amplify-cli/issues/2280#issuecomment-532519270
