### ISSUE TITLE
Why did you remove authentication from this repo? 

### ISSUE THREAD

**Issue by pedroapfilho** [dabit3/aws-appsync-react-workshop#4]
I was seeing your talk but I checked here that you removed the `subscriptions` part, why?

**Comment by pedroapfilho** [comment]
This error was appearing when I was following the workshop and tried the "subscription" part:

```
"Connection failed: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed."
```

**Comment by sgriffiths** [comment]
The subscription part is located in this workshop:
https://github.com/dabit3/aws-amplify-workshop-react#graphql-subscriptions
